image: ubuntu

stages:          # List of stages for jobs, and their order of execution
  - build
  - test

build-job:       # This job runs in the build stage, which runs first.
  stage: build
  script:
    - echo "Compiling XIOS..."
    - apt update
    - apt -yq install $(<dependencies)
    - python3 -c 'import unittest; print(unittest)'
    - ./make_xios --job 2 --debug --arch GCC_LINUX_APT
    - ls -l bin/
    - echo "Compile complete."
  cache:
    key: binaries-cache-$CI_COMMIT_REF_SLUG
    paths:
      - bin/*

test-job:   # This job runs in the test stage.
  stage: test    # It only starts when the job in the build stage completes successfully.
  script:
    - apt update
    - apt -yq install $(<dependencies)
    - python3 -c 'import unittest; print(unittest)'
    - ls -lh bin/
    - echo 'Run mpiexec as root, against openmpi advice'
    - export OMPI_ALLOW_RUN_AS_ROOT=1
    - export OMPI_ALLOW_RUN_AS_ROOT_CONFIRM=1
    - echo "Running test suite... This will take about ?? seconds."
    - export GITHUB_ACTION_LIMIT_RANKS=1
    - python3 -m xios_test_suite.pyTestingFramework
  cache:
    key: binaries-cache-$CI_COMMIT_REF_SLUG
    paths:
      - bin/*
